nycmeshnet/k8s-infra

- ansible/roles/mesh-k8s-node/tasks/main.yaml
Justification: working on integration tests to increase visibility into system performance and operation
> Add WN key

- terraform/mesh_cluster/ansible.tf
The last place I hardcoded the count
> One more value

- terraform/dev3.tfvars
- terraform/prod1.tfvars
**Merge several hours after  #11**
> Increase disk size on node 1

- ansible/roles/k8s-lb/templates/haproxy.cfg
Add http health check:
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/service-reliability/health-checks/
> Add healthcheck for haproxy

- terraform/dev3.tfvars
- terraform/prod1.tfvars
**Merge several hours after  #12**
> Increase disk size on node 0

- ansible/roles/mesh-k8s-node/tasks/main.yaml
Related to https://github.com/nycmeshnet/meshdb/issues/343
> Install cryptsetup

- ansible/roles/ssh-config/tasks/main.yaml
Disable password auth with sshd
> Disable password auth

- terraform/mesh_cluster/lb.tf
- terraform/mesh_cluster/mgr.tf
- terraform/mesh_cluster/workers.tf
Add tag to indicate the VMs are managed by IaC
> Add managed_by_iac tag

- terraform/cluster.tf
Add the variable I forgot to add.
> Fix site var

- ansible/roles/k8s-lb/templates/haproxy.cfg
- terraform/prod1.tfvars
Uses stats-new.nycmesh.net for testing
> Add Grafana to haproxy.cfg

- ansible/roles/k8s-lb/templates/haproxy.cfg
Redirect `wiki.mesh.nycmesh.net` -> `wiki.nycmesh.net`
> Wiki redirect

- terraform/prod1.tfvars
Get a cert for the `wiki.mesh.nycmesh.net`
Only merge after: https://github.com/nycmeshnet/nycmesh-dns/pull/98
> Add domain for the cert

- ansible/roles/k8s-lb/files/haproxy.d_conf.yaml
- ansible/roles/k8s-lb/tasks/main.yaml
- ansible/roles/k8s-lb/templates/haproxy.cfg
Collect metrics from HA Proxy
https://docs.datadoghq.com/integrations/haproxy/
> Collect metrics from haproxy

- .github/workflows/deploy_environments.yaml
- .github/workflows/deploy_k8s_cluster.yaml
- ansible/ansible.cfg
- ansible/k8s_infra.yaml
Decrease deployment time by 78%
- Add profiling - [902.89s (before)](https://github.com/nycmeshnet/k8s-infra/actions/runs/11874681280/job/33090968919#step:14:1793)
- Gather less facts - [576.49s (-36%)](https://github.com/nycmeshnet/k8s-infra/actions/runs/11875029619/job/33091732904#step:14:1787)
- Gather less facts + hold onto connection - [221.52s (-75%)](https://github.com/nycmeshnet/k8s-infra/actions/runs/11875105572/job/33091958494#step:14:1787)
- Gather less facts + hold onto connection  + pipelining - [190.17s (-78.93%)](https://github.com/nycmeshnet/k8s-infra/actions/runs/11875174538/job/33092042609#step:14:1790)
> Optimize ansible

- ansible/roles/k8s-lb/templates/haproxy.cfg
Cleanup various info disclosures.
> Keep bots guessing

- terraform/prod1.tfvars
- terraform/prod2.tfvars
> Forms to sn3

- terraform/prod1.tfvars
- terraform/prod2.tfvars
> Move forms back to sn10

- ansible/roles/k8s-lb/templates/haproxy.cfg
- terraform/prod1.tfvars
One commit to add gsg-displays backend, acl, and fqdn
> Add gsg-displays reverse proxy

- .github/workflows/deploy_environments.yaml
Turning it off to reduce load on Jon
> Disable gamma1

- terraform/dev3.tfvars
- terraform/prod1.tfvars
Add domains to LBs to get Let's Encrypt certs.
> Add nyckml domains

- ansible/roles/k8s_lb/templates/haproxy.cfg
- terraform/prod1.tfvars
Moved mastodon from Grand St to SN3 (jon)
> Update mastodon internal IP in haproxy.cfg

- terraform/prod1.tfvars
- terraform/prod2.tfvars
> Move stuff back to SN10

- ansible/roles/k8s_cluster_helm/templates/datadog_agent.yaml.j2
Reverts nycmeshnet/k8s-infra#88
> Revert "Delete single step APM instrumentation"

- terraform/prod1.tfvars
> Make the mgr bigger

- ansible/roles/k8s_lb/templates/haproxy.cfg
- terraform/dev3.tfvars
- terraform/mesh_cluster/ansible.tf
- terraform/prod1.tfvars
Only merge AFTER https://github.com/nycmeshnet/nycmesh-dns/pull/228
> Add internal domain
